/// <reference lib="webworker" />
declare const self: ServiceWorkerGlobalScope;

import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';

self.skipWaiting();
clientsClaim();

cleanupOutdatedCaches();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Handle Push Notifications
self.addEventListener('push', (event) => {
    console.log('[sw.ts] Push received', event);
    const payload = event.data?.json() ?? {};
    console.log('[sw.ts] Push payload:', payload);

    // Support both flattened and nested data structure
    const { title, body, url } = payload.data || payload;

    event.waitUntil(
        self.registration.showNotification(title || 'New Notification', {
            body: body || 'Check your revisions!',
            icon: '/icon-192x192.png',
            badge: '/icon-192x192.png',
            data: { url: url || '/' },
            tag: 'revision-reminder',
            renotify: true
        } as any)
    );
});

// Handle Notification Click - Focus App
self.addEventListener('notificationclick', (event) => {
    event.notification.close();

    event.waitUntil(
        self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
            // Check if there's already a tab open
            for (const client of clientList) {
                // Focus the first window that matches our scope
                if (client.url.startsWith(self.registration.scope) && 'focus' in client) {
                    return client.focus();
                }
            }
            // If no window is open, open a new one
            if (self.clients.openWindow) {
                return self.clients.openWindow('/');
            }
        })
    );
});
